main:
  push:
    - imports: https://cnb.cool/makotowu/tencentcloud-wordpress-plugin-captcha-secret/-/blob/main/env.yml
      stages:
        - name: sync to github
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/makotowu/tencentcloud-wordpress-plugin-captcha.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}