# .cnb.yml
main:
  push:
    - imports: https://cnb.cool/makotowu/tencentcloud-wordpress-plugin-captcha-secret/-/blob/main/env.yml
      stages:
        # 1. 代码同步到 GitHub
        - name: sync to github
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/makotowu/tencentcloud-wordpress-plugin-captcha.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}
            branch: main
            sync_mode: rebase

        # 2. 自动生成 Tag 和版本号（依赖提交信息）
        - name: auto-tag
          image: cnbcool/git-auto-tag:latest
          settings:
            tagFormat: v\${version}  # 版本号格式（如 v1.0.0）
            branch: main           # 基于 main 分支生成 Tag
            repoUrlHttps: https://github.com/makotowu/tencentcloud-wordpress-plugin-captcha.git  # 目标仓库 HTTPS 地址
            releaseRules: |        # 自定义版本增长规则
              - type: feat
                scope: ""
                release: major   # feat 提交触发主版本增长
              - type: fix
                scope: ""
                release: patch   # fix 提交触发补丁版本增长
            toFile: tag_info.json  # 保存结果到文件（可选）

        # 3. 创建 Release（需提前配置版本号变量）
        - name: create release
          type: git:release
          options:
            tag: ${CNB_VERSION}      # 版本号变量（如 v1.0.0）
            title: "Release ${CNB_VERSION}"
            description: "Auto-generated by CNB"
            latest: true             # 设为最新版本