$:
  # vscode 事件：专供页面中启动远程开发用
  vscode:
    - docker:
        # 自定义镜像作为开发环境
        image: cnbcool/default-dev-env:latest
      services:
        - vscode
        - docker
      runner :
        cpus: 1